version: '3.10.0'
services:
  app:
    build: .
    ports:
      - 8080:8080
    
    image: app:assignment-online
    container_name: assignment-online
    command: python manage.py runserver 0.0.0.0:8080
  
  db:
  image: mariadb:latest
  container_name: assignment-online-db
  restart: always
  ports:
    - 3306:3306
  # other settings
  environment:
    MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    MYSQL_DATABASE: ${DB_NAME}
    MYSQL_USER: ${DB_USER}
    MYSQL_PASSWORD: ${DB_PASS}