version: '3.10.0'
services:
  app:
    build: .
    ports:
      - 8080:8080
    image: app:assignment-online
    container_name: assignment-online
    command:
      - /bin/sh
      - -c
      - |
        wait-for-it --service db:3306 --timeout=60
        python manage.py migrate
        python manage.py runserver 127.0.0.1:8080
    depends_on:
      - db
  
  db:
    image: mariadb:latest
    container_name: assignment-online-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      
      