# Generated by Django 4.1.4 on 2023-01-16 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_remove_student_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='matiere',
            name='enrolled',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('admin', 'admin')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
