# Generated by Django 4.1.4 on 2023-01-17 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_rename_date_exam_create_date_rename_name_exam_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='enrolled',
        ),
        migrations.AddField(
            model_name='matiere',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
