# Generated by Django 4.1.4 on 2023-01-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_attempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='user',
        ),
    ]
