# Generated by Django 4.1.4 on 2023-01-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_matiere_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
    ]
