# Generated by Django 4.1.4 on 2023-01-19 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_question_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempter',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
