# Generated by Django 4.1.4 on 2023-01-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_attempter_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempter',
            name='completed',
            field=models.DateTimeField(choices=[('yes', 'yes'), ('no', 'no')], default='yes'),
        ),
    ]
