# Generated by Django 4.1.4 on 2023-01-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_attempter_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempter',
            name='completed',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=1000),
        ),
    ]
