# Generated by Django 4.1.4 on 2023-01-19 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_attempter_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='groupe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.group'),
        ),
    ]
